// Port-accurate stub of the Bazel/Chisel-generated CoreMiniAxi for lint only.
module CoreMiniAxi (
  input  logic         io_aclk,
  input  logic         io_aresetn,
  input  logic         io_te,
  input  logic [31:0]  io_boot_addr,
  input  logic         io_irq,
  output logic         io_halted,
  output logic         io_fault,
  output logic         io_wfi,

  input  logic         io_dm_req_valid,
  output logic         io_dm_req_ready,
  input  logic [31:0]  io_dm_req_bits_address,
  input  logic [31:0]  io_dm_req_bits_data,
  input  logic [1:0]   io_dm_req_bits_op,
  output logic         io_dm_rsp_valid,
  input  logic         io_dm_rsp_ready,
  output logic [31:0]  io_dm_rsp_bits_data,
  output logic [1:0]   io_dm_rsp_bits_op,

  output logic         io_axi_master_write_addr_valid,
  input  logic         io_axi_master_write_addr_ready,
  output logic [31:0]  io_axi_master_write_addr_bits_addr,
  output logic [2:0]   io_axi_master_write_addr_bits_prot,
  output logic [5:0]   io_axi_master_write_addr_bits_id,
  output logic [7:0]   io_axi_master_write_addr_bits_len,
  output logic [2:0]   io_axi_master_write_addr_bits_size,
  output logic [1:0]   io_axi_master_write_addr_bits_burst,
  output logic         io_axi_master_write_addr_bits_lock,
  output logic [3:0]   io_axi_master_write_addr_bits_cache,
  output logic [3:0]   io_axi_master_write_addr_bits_qos,
  output logic [3:0]   io_axi_master_write_addr_bits_region,
  output logic         io_axi_master_write_data_valid,
  input  logic         io_axi_master_write_data_ready,
  output logic [127:0] io_axi_master_write_data_bits_data,
  output logic [15:0]  io_axi_master_write_data_bits_strb,
  output logic         io_axi_master_write_data_bits_last,
  input  logic         io_axi_master_write_resp_valid,
  output logic         io_axi_master_write_resp_ready,
  input  logic [5:0]   io_axi_master_write_resp_bits_id,
  input  logic [1:0]   io_axi_master_write_resp_bits_resp,
  output logic         io_axi_master_read_addr_valid,
  input  logic         io_axi_master_read_addr_ready,
  output logic [31:0]  io_axi_master_read_addr_bits_addr,
  output logic [2:0]   io_axi_master_read_addr_bits_prot,
  output logic [5:0]   io_axi_master_read_addr_bits_id,
  output logic [7:0]   io_axi_master_read_addr_bits_len,
  output logic [2:0]   io_axi_master_read_addr_bits_size,
  output logic [1:0]   io_axi_master_read_addr_bits_burst,
  output logic         io_axi_master_read_addr_bits_lock,
  output logic [3:0]   io_axi_master_read_addr_bits_cache,
  output logic [3:0]   io_axi_master_read_addr_bits_qos,
  output logic [3:0]   io_axi_master_read_addr_bits_region,
  input  logic         io_axi_master_read_data_valid,
  output logic         io_axi_master_read_data_ready,
  input  logic [127:0] io_axi_master_read_data_bits_data,
  input  logic [5:0]   io_axi_master_read_data_bits_id,
  input  logic [1:0]   io_axi_master_read_data_bits_resp,
  input  logic         io_axi_master_read_data_bits_last,

  input  logic         io_axi_slave_write_addr_valid,
  output logic         io_axi_slave_write_addr_ready,
  input  logic [31:0]  io_axi_slave_write_addr_bits_addr,
  input  logic [2:0]   io_axi_slave_write_addr_bits_prot,
  input  logic [5:0]   io_axi_slave_write_addr_bits_id,
  input  logic [7:0]   io_axi_slave_write_addr_bits_len,
  input  logic [2:0]   io_axi_slave_write_addr_bits_size,
  input  logic [1:0]   io_axi_slave_write_addr_bits_burst,
  input  logic         io_axi_slave_write_addr_bits_lock,
  input  logic [3:0]   io_axi_slave_write_addr_bits_cache,
  input  logic [3:0]   io_axi_slave_write_addr_bits_qos,
  input  logic [3:0]   io_axi_slave_write_addr_bits_region,
  input  logic         io_axi_slave_write_data_valid,
  output logic         io_axi_slave_write_data_ready,
  input  logic [127:0] io_axi_slave_write_data_bits_data,
  input  logic [15:0]  io_axi_slave_write_data_bits_strb,
  input  logic         io_axi_slave_write_data_bits_last,
  output logic         io_axi_slave_write_resp_valid,
  input  logic         io_axi_slave_write_resp_ready,
  output logic [5:0]   io_axi_slave_write_resp_bits_id,
  output logic [1:0]   io_axi_slave_write_resp_bits_resp,
  input  logic         io_axi_slave_read_addr_valid,
  output logic         io_axi_slave_read_addr_ready,
  input  logic [31:0]  io_axi_slave_read_addr_bits_addr,
  input  logic [2:0]   io_axi_slave_read_addr_bits_prot,
  input  logic [5:0]   io_axi_slave_read_addr_bits_id,
  input  logic [7:0]   io_axi_slave_read_addr_bits_len,
  input  logic [2:0]   io_axi_slave_read_addr_bits_size,
  input  logic [1:0]   io_axi_slave_read_addr_bits_burst,
  input  logic         io_axi_slave_read_addr_bits_lock,
  input  logic [3:0]   io_axi_slave_read_addr_bits_cache,
  input  logic [3:0]   io_axi_slave_read_addr_bits_qos,
  input  logic [3:0]   io_axi_slave_read_addr_bits_region,
  output logic         io_axi_slave_read_data_valid,
  input  logic         io_axi_slave_read_data_ready,
  output logic [127:0] io_axi_slave_read_data_bits_data,
  output logic [5:0]   io_axi_slave_read_data_bits_id,
  output logic [1:0]   io_axi_slave_read_data_bits_resp,
  output logic         io_axi_slave_read_data_bits_last
);
endmodule
