// Coral NPU (google-coral/coralnpu, CoreMiniAxi) as a Chipyard peripheral.
//
// The NPU is integrated as a SystemVerilog blackbox generated by Coral's own
// bazel flow (see platforms/chipyard/export-coralnpu-sv.sh in the coralnpu
// repo). Nothing from Coral's Chisel is compiled here.
//
//   * AXI4 slave  (ITCM / DTCM / CSR)  -> periphery bus, fixed 256 KiB window
//   * AXI4 master (NPU -> main memory) -> front bus client
//   * halted / fault                   -> PLIC interrupt sources (2)
//   * control block (TL register node) -> async reset + irq + status readback
//
// Same clock domain as the buses (the default Chipyard config ties sbus/pbus/
// fbus into one "uncore" clock group). No CDC.
package chipyard.example

import chisel3._
import chisel3.util._
import freechips.rocketchip.amba.axi4._
import freechips.rocketchip.diplomacy.{AddressSet, BufferParams, IdRange, RegionType, TransferSizes}
import org.chipsalliance.diplomacy.lazymodule.{LazyModule, LazyModuleImp}
import freechips.rocketchip.interrupts._
import freechips.rocketchip.regmapper.{RegField, RegFieldDesc}
import freechips.rocketchip.resources.SimpleDevice
import freechips.rocketchip.subsystem.{BaseSubsystem, PBUS, FBUS}
import freechips.rocketchip.tilelink._
import freechips.rocketchip.util._
import org.chipsalliance.cde.config.{Parameters, Field, Config}
import testchipip.soc.{SubsystemInjector, SubsystemInjectorKey}

/** Parameters. Widths are the ones CoreMiniAxi is generated with
  * (--lsuDataBits=128, axi2IdBits=6, 32-bit addresses). Do not change them
  * without regenerating the SV: AXI width mismatches hang silently.
  */
case class CoralNPUParams(
  base:        BigInt = 0x60000000L,   // AXI slave window: ITCM @+0x0, DTCM @+0x10000, CSR @+0x30000
  ctrlBase:    BigInt = 0x60040000L,   // 4 KiB control/status block (this wrapper)
  addrBits:    Int    = 32,
  dataBits:    Int    = 128,
  idBits:      Int    = 6,
  maxFlight:   Int    = 8,             // per-ID cap applied to the NPU master port
  moduleName:  String = "CoreMiniAxi",
  // Colon-separated list of SV files to add as blackbox sources, from the
  // CORALNPU_SV environment variable at elaboration time.
  svFiles:     Seq[String] = sys.env.get("CORALNPU_SV").map(_.split(":").toSeq.filter(_.nonEmpty)).getOrElse(Nil))
{
  val windowBytes: BigInt = 0x40000
  require(dataBits == 128, "CoreMiniAxi is generated with a 128-bit AXI data bus")
  require(isPow2(windowBytes))
}

case object CoralNPUKey extends Field[Option[CoralNPUParams]](None)

// ---------------------------------------------------------------------------
// Blackbox IO. Field names mirror Coral's AxiMasterIO (hdl/chisel/src/bus/Axi.scala)
// so Chisel's flattening reproduces the generated port names exactly, e.g.
// io_axi_slave_write_addr_bits_addr. Verify with tools/check_ports.py.
// ---------------------------------------------------------------------------
class CoralNPUAxiA(addrBits: Int, idBits: Int) extends Bundle {
  val addr   = UInt(addrBits.W)
  val prot   = UInt(3.W)
  val id     = UInt(idBits.W)
  val len    = UInt(8.W)
  val size   = UInt(3.W)
  val burst  = UInt(2.W)
  val lock   = UInt(1.W)
  val cache  = UInt(4.W)
  val qos    = UInt(4.W)
  val region = UInt(4.W)
}
class CoralNPUAxiW(dataBits: Int) extends Bundle {
  val data = UInt(dataBits.W)
  val last = Bool()
  val strb = UInt((dataBits / 8).W)
}
class CoralNPUAxiB(idBits: Int) extends Bundle {
  val id   = UInt(idBits.W)
  val resp = UInt(2.W)
}
class CoralNPUAxiR(dataBits: Int, idBits: Int) extends Bundle {
  val data = UInt(dataBits.W)
  val id   = UInt(idBits.W)
  val resp = UInt(2.W)
  val last = Bool()
}
class CoralNPUAxiWriteIO(addrBits: Int, dataBits: Int, idBits: Int) extends Bundle {
  val addr = Decoupled(new CoralNPUAxiA(addrBits, idBits))
  val data = Decoupled(new CoralNPUAxiW(dataBits))
  val resp = Flipped(Decoupled(new CoralNPUAxiB(idBits)))
}
class CoralNPUAxiReadIO(addrBits: Int, dataBits: Int, idBits: Int) extends Bundle {
  val addr = Decoupled(new CoralNPUAxiA(addrBits, idBits))
  val data = Flipped(Decoupled(new CoralNPUAxiR(dataBits, idBits)))
}
class CoralNPUAxiMasterIO(addrBits: Int, dataBits: Int, idBits: Int) extends Bundle {
  val write = new CoralNPUAxiWriteIO(addrBits, dataBits, idBits)
  val read  = new CoralNPUAxiReadIO(addrBits, dataBits, idBits)
}

class CoreMiniAxiBlackBox(params: CoralNPUParams) extends BlackBox with HasBlackBoxPath {
  override def desiredName = params.moduleName
  val io = IO(new Bundle {
    val io_aclk       = Input(Clock())
    val io_aresetn    = Input(AsyncReset())
    val io_axi_slave  = Flipped(new CoralNPUAxiMasterIO(params.addrBits, params.dataBits, params.idBits))
    val io_axi_master = new CoralNPUAxiMasterIO(params.addrBits, params.dataBits, params.idBits)
    val io_halted     = Output(Bool())
    val io_fault      = Output(Bool())
    val io_wfi        = Output(Bool())
    val io_irq        = Input(Bool())
    val io_boot_addr  = Input(UInt(32.W))
    val io_te         = Input(Bool())
    // Debug-module request/response port: tied off (no external debugger).
    val io_dm_req_valid        = Input(Bool())
    val io_dm_req_ready        = Output(Bool())
    val io_dm_req_bits_address = Input(UInt(32.W))
    val io_dm_req_bits_data    = Input(UInt(32.W))
    val io_dm_req_bits_op      = Input(UInt(2.W))
    val io_dm_rsp_valid        = Output(Bool())
    val io_dm_rsp_ready        = Input(Bool())
    val io_dm_rsp_bits_data    = Output(UInt(32.W))
    val io_dm_rsp_bits_op      = Output(UInt(2.W))
    // io_debug_* (instruction trace) are outputs only and are deliberately
    // left unlisted / unconnected.
  })
  if (params.svFiles.isEmpty) {
    println("[CoralNPU] WARNING: CORALNPU_SV is not set; no blackbox sources were added for " + params.moduleName)
  }
  params.svFiles.foreach(addPath)
}

// ---------------------------------------------------------------------------
// Diplomatic wrapper
// ---------------------------------------------------------------------------
class CoralNPU(params: CoralNPUParams, pbusBeatBytes: Int)(implicit p: Parameters) extends LazyModule {
  val beatBytes = params.dataBits / 8
  val device = new SimpleDevice("coralnpu", Seq("google,coralnpu-v2"))

  // ITCM / DTCM / CSR window. Single-beat transfers only; TLFragmenter +
  // TLWidthWidget on the pbus side produce exactly that.
  val slaveNode = AXI4SlaveNode(Seq(AXI4SlavePortParameters(
    slaves = Seq(AXI4SlaveParameters(
      address       = Seq(AddressSet(params.base, params.windowBytes - 1)),
      resources     = device.reg("mem"),
      regionType    = RegionType.UNCACHED,
      executable    = true,
      supportsWrite = TransferSizes(1, beatBytes),
      supportsRead  = TransferSizes(1, beatBytes),
      interleavedId = Some(0))),
    beatBytes = beatBytes)))

  // NPU -> system memory. IDs 0 (data) and 1 (fetch) are used by the core;
  // declare the full 6-bit range the port carries.
  val masterNode = AXI4MasterNode(Seq(AXI4MasterPortParameters(
    masters = Seq(AXI4MasterParameters(
      name = "coralnpu",
      id   = IdRange(0, 1 << params.idBits))))))

  // 0: halted, 1: fault (level)
  val intnode = IntSourceNode(IntSourcePortSimple(num = 2, resources = device.int))

  // Control/status block owned by this wrapper.
  val ctrlNode = TLRegisterNode(
    address   = Seq(AddressSet(params.ctrlBase, 0xfff)),
    device    = device,
    deviceKey = "reg/control",
    beatBytes = pbusBeatBytes)

  lazy val module = new Impl
  class Impl extends LazyModuleImp(this) {
    val (s, _)    = slaveNode.in(0)
    val (m, _)    = masterNode.out(0)
    val (ints, _) = intnode.out(0)

    val core = Module(new CoreMiniAxiBlackBox(params))

    // Power-on: NPU held in (async) reset until software clears soft_reset.
    val softReset = RegInit(1.U(1.W))
    val irqReg    = RegInit(0.U(1.W))

    core.io.io_aclk    := clock
    core.io.io_aresetn := (!(reset.asBool || softReset(0))).asAsyncReset
    core.io.io_irq     := irqReg(0)
    core.io.io_boot_addr := 0.U        // ITCM base; PC_START CSR overrides anyway
    core.io.io_te      := false.B
    core.io.io_dm_req_valid        := false.B
    core.io.io_dm_req_bits_address := 0.U
    core.io.io_dm_req_bits_data    := 0.U
    core.io.io_dm_req_bits_op      := 0.U
    core.io.io_dm_rsp_ready        := true.B

    def fit(x: UInt, w: Int): UInt = if (w == 0) 0.U else if (w >= x.getWidth) x else x(w - 1, 0)
    val winMask = (params.windowBytes - 1).U(params.addrBits.W)
    def localAddr(a: UInt): UInt = fit(a.pad(params.addrBits), params.addrBits) & winMask

    // ---- AXI4 slave: SoC (s) -> NPU (sl) ---------------------------------
    val sl = core.io.io_axi_slave
    sl.write.addr.valid       := s.aw.valid
    s.aw.ready                := sl.write.addr.ready
    sl.write.addr.bits.addr   := localAddr(s.aw.bits.addr)
    sl.write.addr.bits.prot   := s.aw.bits.prot
    sl.write.addr.bits.id     := s.aw.bits.id
    sl.write.addr.bits.len    := s.aw.bits.len
    sl.write.addr.bits.size   := s.aw.bits.size
    sl.write.addr.bits.burst  := s.aw.bits.burst
    sl.write.addr.bits.lock   := s.aw.bits.lock
    sl.write.addr.bits.cache  := s.aw.bits.cache
    sl.write.addr.bits.qos    := s.aw.bits.qos
    sl.write.addr.bits.region := 0.U

    sl.write.data.valid     := s.w.valid
    s.w.ready               := sl.write.data.ready
    sl.write.data.bits.data := s.w.bits.data
    sl.write.data.bits.strb := s.w.bits.strb
    sl.write.data.bits.last := s.w.bits.last

    s.b.valid            := sl.write.resp.valid
    sl.write.resp.ready  := s.b.ready
    s.b.bits             := DontCare
    s.b.bits.id          := fit(sl.write.resp.bits.id, s.b.bits.id.getWidth)
    s.b.bits.resp        := sl.write.resp.bits.resp

    sl.read.addr.valid       := s.ar.valid
    s.ar.ready               := sl.read.addr.ready
    sl.read.addr.bits.addr   := localAddr(s.ar.bits.addr)
    sl.read.addr.bits.prot   := s.ar.bits.prot
    sl.read.addr.bits.id     := s.ar.bits.id
    sl.read.addr.bits.len    := s.ar.bits.len
    sl.read.addr.bits.size   := s.ar.bits.size
    sl.read.addr.bits.burst  := s.ar.bits.burst
    sl.read.addr.bits.lock   := s.ar.bits.lock
    sl.read.addr.bits.cache  := s.ar.bits.cache
    sl.read.addr.bits.qos    := s.ar.bits.qos
    sl.read.addr.bits.region := 0.U

    s.r.valid           := sl.read.data.valid
    sl.read.data.ready  := s.r.ready
    s.r.bits            := DontCare
    s.r.bits.id         := fit(sl.read.data.bits.id, s.r.bits.id.getWidth)
    s.r.bits.data       := sl.read.data.bits.data
    s.r.bits.resp       := sl.read.data.bits.resp
    s.r.bits.last       := sl.read.data.bits.last

    // ---- AXI4 master: NPU (ma) -> SoC (m) --------------------------------
    val ma = core.io.io_axi_master
    m.aw.valid          := ma.write.addr.valid
    ma.write.addr.ready := m.aw.ready
    m.aw.bits           := DontCare
    m.aw.bits.addr      := ma.write.addr.bits.addr
    m.aw.bits.id        := ma.write.addr.bits.id
    m.aw.bits.len       := ma.write.addr.bits.len
    m.aw.bits.size      := ma.write.addr.bits.size
    m.aw.bits.burst     := ma.write.addr.bits.burst
    m.aw.bits.lock      := ma.write.addr.bits.lock
    m.aw.bits.cache     := ma.write.addr.bits.cache
    m.aw.bits.prot      := ma.write.addr.bits.prot
    m.aw.bits.qos       := ma.write.addr.bits.qos

    m.w.valid           := ma.write.data.valid
    ma.write.data.ready := m.w.ready
    m.w.bits            := DontCare
    m.w.bits.data       := ma.write.data.bits.data
    m.w.bits.strb       := ma.write.data.bits.strb
    m.w.bits.last       := ma.write.data.bits.last

    ma.write.resp.valid     := m.b.valid
    m.b.ready               := ma.write.resp.ready
    ma.write.resp.bits.id   := m.b.bits.id
    ma.write.resp.bits.resp := m.b.bits.resp

    m.ar.valid          := ma.read.addr.valid
    ma.read.addr.ready  := m.ar.ready
    m.ar.bits           := DontCare
    m.ar.bits.addr      := ma.read.addr.bits.addr
    m.ar.bits.id        := ma.read.addr.bits.id
    m.ar.bits.len       := ma.read.addr.bits.len
    m.ar.bits.size      := ma.read.addr.bits.size
    m.ar.bits.burst     := ma.read.addr.bits.burst
    m.ar.bits.lock      := ma.read.addr.bits.lock
    m.ar.bits.cache     := ma.read.addr.bits.cache
    m.ar.bits.prot      := ma.read.addr.bits.prot
    m.ar.bits.qos       := ma.read.addr.bits.qos

    ma.read.data.valid     := m.r.valid
    m.r.ready              := ma.read.data.ready
    ma.read.data.bits.data := m.r.bits.data
    ma.read.data.bits.id   := m.r.bits.id
    ma.read.data.bits.resp := m.r.bits.resp
    ma.read.data.bits.last := m.r.bits.last

    // ---- interrupts --------------------------------------------------------
    ints(0) := core.io.io_halted
    ints(1) := core.io.io_fault

    // ---- control / status block --------------------------------------------
    // 0x0 CTRL   [0] soft_reset (RW, por=1: NPU held in reset) [1] irq (RW)
    // 0x4 STATUS [0] halted (RO) [1] fault (RO) [2] wfi (RO)
    ctrlNode.regmap(
      0x00 -> Seq(
        RegField(1, softReset, RegFieldDesc("soft_reset", "1 = assert NPU aresetn (power-on value 1)", reset = Some(BigInt(1)))),
        RegField(1, irqReg,    RegFieldDesc("irq", "Level interrupt request into the NPU"))),
      0x04 -> Seq(
        RegField.r(1, core.io.io_halted.asUInt, RegFieldDesc("halted", "NPU halted (mpause)", volatile = true)),
        RegField.r(1, core.io.io_fault.asUInt,  RegFieldDesc("fault",  "NPU fault",           volatile = true)),
        RegField.r(1, core.io.io_wfi.asUInt,    RegFieldDesc("wfi",    "NPU in WFI",          volatile = true))))
  }
}

// ---------------------------------------------------------------------------
// Attachment via the SubsystemInjector API (no DigitalTop edit required).
// ---------------------------------------------------------------------------
case object CoralNPUInjector extends SubsystemInjector((p, baseSubsystem) => {
  p(CoralNPUKey).foreach { params =>
    implicit val q: Parameters = p
    val pbus = baseSubsystem.locateTLBusWrapper(PBUS)
    val fbus = baseSubsystem.locateTLBusWrapper(FBUS)
    val npu  = pbus { LazyModule(new CoralNPU(params, pbus.beatBytes)) }

    // pbus -> NPU AXI4 slave. Same adapter chain as rocket-chip's memory AXI4
    // port (UserYanker + IdIndexer) plus the width/fragment stages the GCD
    // AXI4 example uses.
    pbus.coupleTo("coralnpu_slave") {
      (npu.slaveNode
        := AXI4Buffer()
        := AXI4UserYanker()
        := AXI4IdIndexer(params.idBits)
        := TLToAXI4()
        := TLWidthWidget(pbus.beatBytes)
        := TLFragmenter(pbus.beatBytes, pbus.blockBytes, holdFirstDeny = true)
        := _)
    }

    pbus.coupleTo("coralnpu_ctrl") {
      npu.ctrlNode := TLFragmenter(pbus.beatBytes, pbus.blockBytes) := _
    }

    // NPU AXI4 master -> fbus. Same chain as rocket-chip's CanHaveSlaveAXI4Port.
    fbus.coupleFrom("coralnpu_master") {
      (_
        := TLBuffer(BufferParams.default)
        := TLFIFOFixer(TLFIFOFixer.all)
        := TLWidthWidget(params.dataBits / 8)
        := AXI4ToTL()
        := AXI4UserYanker(Some(params.maxFlight))
        := AXI4Fragmenter()
        := AXI4IdIndexer(1)
        := AXI4Buffer()
        := npu.masterNode)
    }

    baseSubsystem.ibus.fromSync := npu.intnode
  }
})

class WithCoralNPU extends Config((site, here, up) => {
  case CoralNPUKey => Some(CoralNPUParams())
  case SubsystemInjectorKey => up(SubsystemInjectorKey) + CoralNPUInjector
})

class WithCoralNPUAt(base: BigInt, ctrlBase: BigInt) extends Config((site, here, up) => {
  case CoralNPUKey => Some(CoralNPUParams(base = base, ctrlBase = ctrlBase))
  case SubsystemInjectorKey => up(SubsystemInjectorKey) + CoralNPUInjector
})
