#!/usr/bin/env bash
# Assemble the Coral NPU smoke-test firmware to a flat binary and a C header.
# Uses clang's integrated RISC-V assembler (no RISC-V gcc needed).
# -march=rv32imf: NO 'c' extension (Coral NPU reclaims that encoding space).
set -euo pipefail
cd "$(dirname "$0")"
CLANG=${CLANG:-clang}
OBJCOPY=${OBJCOPY:-$(command -v llvm-objcopy || command -v llvm-objcopy-18)}
OBJDUMP=${OBJDUMP:-$(command -v llvm-objdump || command -v llvm-objdump-18)}
$CLANG --target=riscv32 -march=rv32imf -mabi=ilp32f -c coralnpu_fw.S -o coralnpu_fw.o
$OBJCOPY -O binary --only-section=.text coralnpu_fw.o coralnpu_fw.bin
$OBJDUMP -d coralnpu_fw.o > coralnpu_fw.dis
# Refuse any 16-bit (compressed) encoding: every instruction must be 4 bytes.
if grep -E '^\s+[0-9a-f]+:\s+[0-9a-f]{2} [0-9a-f]{2}\s+\S' coralnpu_fw.dis | grep -vqE '[0-9a-f]{2} [0-9a-f]{2} [0-9a-f]{2} [0-9a-f]{2}'; then
  echo "ERROR: compressed instruction found" >&2; exit 1
fi
python3 - <<'PY'
import struct
data = open("coralnpu_fw.bin", "rb").read()
assert len(data) % 4 == 0, "firmware not word aligned"
words = struct.unpack("<%dI" % (len(data)//4), data)
with open("coralnpu_fw.h", "w") as f:
    f.write("// Generated by build-fw.sh from coralnpu_fw.S. Do not edit.\n")
    f.write("#ifndef CORALNPU_FW_H\n#define CORALNPU_FW_H\n#include <stdint.h>\n")
    f.write("#define CORALNPU_FW_WORDS %d\n" % len(words))
    f.write("#define CORALNPU_FW_EXPECT0 0x6688AACCu\n#define CORALNPU_FW_EXPECT1 0x40700000u\n#define CORALNPU_FW_EXPECT2 0xC0DE0001u\n")
    f.write("static const uint32_t coralnpu_fw[CORALNPU_FW_WORDS] = {\n")
    for i, w in enumerate(words):
        f.write("  0x%08x,%s" % (w, "\n" if i % 4 == 3 else " "))
    f.write("\n};\n#endif\n")
print("firmware: %d bytes, %d words" % (len(data), len(words)))
PY
