// Generated by build-fw.sh from coralnpu_fw.S. Do not edit.
#ifndef CORALNPU_FW_H
#define CORALNPU_FW_H
#include <stdint.h>
#define CORALNPU_FW_WORDS 19
#define CORALNPU_FW_EXPECT0 0x6688AACCu
#define CORALNPU_FW_EXPECT1 0x40700000u
#define CORALNPU_FW_EXPECT2 0xC0DE0001u
static const uint32_t coralnpu_fw[CORALNPU_FW_WORDS] = {
  0x00010537,   0x112232b7,   0x34428293,   0x55667337,
  0x78830313,   0x006283b3,   0x00752023,   0x3fc00e37,
  0xf00e0053,   0x40100eb7,   0xf00e80d3,   0x00107153,
  0xe0010f53,   0x01e52223,   0xc0de0fb7,   0x001f8f93,
  0x01f52423,   0x08000073,   0x0000006f, 
};
#endif
