#!/usr/bin/env bash
# Generate the Coral NPU CoreMiniAxi SystemVerilog with Coral's own bazel flow
# and flatten it (plus its blackbox resources: CVFPU, common_cells, ClockGate,
# RstSync, SRAM models) into ONE file for use as a Chipyard blackbox.
# Run from the coralnpu repo root on a machine with bazel + network access.
#
#   ./platforms/chipyard/export-coralnpu-sv.sh [out dir]   (default: build/coralnpu-sv)
#   ./platforms/chipyard/export-coralnpu-sv.sh --from-dir <dir with CoreMiniAxi.sv + CoreMiniAxi.zip> [out dir]
#   add --fpga for the FireSim/Vivado bundle (`define FPGA_XILINX -> BUFGCE clock gate)
#   export CORALNPU_SV=$PWD/build/coralnpu-sv/coralnpu_core_mini_axi.sv
# --from-dir skips bazel and flattens an emit directory produced by any
# other route (e.g. `sbt runMain coralnpu.EmitCore ...`).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BIN=""; FPGA=0
while [ $# -gt 0 ]; do
  case "$1" in
    --from-dir) BIN="$(cd "$2" && pwd)"; shift 2 ;;
    --fpga)     FPGA=1; shift ;;   # define FPGA_XILINX: ClockGate.sv uses BUFGCE instead of a latch
    *) break ;;
  esac
done
OUT="${1:-$ROOT/build/coralnpu-sv}"
if [ -z "$BIN" ]; then
  TARGET="//hdl/chisel/src/coralnpu:core_mini_axi_cc_library_emit_verilog"
  cd "$ROOT"
  bazel build "$TARGET"
  BIN="$(bazel info bazel-bin)/hdl/chisel/src/coralnpu"
fi
mkdir -p "$OUT/split"
rm -rf "$OUT/split"/*
unzip -q -o "$BIN/CoreMiniAxi.zip" -d "$OUT/split"
cp "$BIN/CoreMiniAxi.sv" "$OUT/split/"
# Order: packages first, then external resources, then the Chisel-emitted
# design (single-file emit already contains every Chisel module, so drop the
# split per-module copies to avoid duplicate definitions).
python3 - "$OUT" "$FPGA" <<'PY'
import os, re, sys
out = sys.argv[1]; split = os.path.join(out, "split"); fpga = sys.argv[2] == "1"
files = []
for d, _, fs in os.walk(split):
    for f in fs:
        if f.endswith((".sv", ".v", ".svh")): files.append(os.path.relpath(os.path.join(d, f), split))
single = open(os.path.join(split, "CoreMiniAxi.sv")).read()
emitted = set(re.findall(r"^module\s+(\w+)", single, re.M))
def is_dup(path):
    txt = open(os.path.join(split, path)).read()
    mods = set(re.findall(r"^module\s+(\w+)", txt, re.M))
    return path != "CoreMiniAxi.sv" and mods and mods <= emitted
keep = [f for f in files if not is_dup(f) and not f.endswith(".f") and not f.startswith("verification/")]
pkgs = sorted(f for f in keep if "_pkg" in f)
rest = sorted(f for f in keep if f not in pkgs and f != "CoreMiniAxi.sv")
order = pkgs + rest + ["CoreMiniAxi.sv"]
with open(os.path.join(out, "coralnpu_core_mini_axi.sv"), "w") as w:
    w.write("// Flattened Coral NPU CoreMiniAxi bundle. Generated by export-coralnpu-sv.sh.\n")
    w.write("`define USE_GENERIC 1\n")
    if fpga: w.write("`define FPGA_XILINX 1\n")
    for f in order:
        w.write("\n// ===== %s =====\n" % f)
        txt = open(os.path.join(split, f)).read()
        # firtool names generated memories generically (ram_<depth>x<width>);
        # Chipyard's own firtool run emits the same names, so prefix ours.
        txt = re.sub(r"\bram_(\d+x\d+)\b", r"coralnpu_ram_\1", txt)
        w.write(txt)
        w.write("\n")
open(os.path.join(out, "coralnpu_core_mini_axi.f"), "w").write("\n".join(order) + "\n")
print("wrote", os.path.join(out, "coralnpu_core_mini_axi.sv"), "from", len(order), "files")
PY
python3 "$ROOT/platforms/chipyard/tools/check_ports.py" "$OUT/coralnpu_core_mini_axi.sv"
echo "export CORALNPU_SV=$OUT/coralnpu_core_mini_axi.sv"
