#!/usr/bin/env bash
# Generate the Coral NPU CoreMiniAxi SystemVerilog with Coral's own bazel flow
# and flatten it (plus its blackbox resources: CVFPU, common_cells, ClockGate,
# RstSync, SRAM models) into ONE file for use as a Chipyard blackbox.
# Run from the coralnpu repo root on a machine with bazel + network access.
#
#   ./platforms/chipyard/export-coralnpu-sv.sh [out dir]   (default: build/coralnpu-sv)
#   export CORALNPU_SV=$PWD/build/coralnpu-sv/coralnpu_core_mini_axi.sv
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="${1:-$ROOT/build/coralnpu-sv}"
TARGET="//hdl/chisel/src/coralnpu:core_mini_axi_cc_library_emit_verilog"
cd "$ROOT"
bazel build "$TARGET"
BIN="$(bazel info bazel-bin)/hdl/chisel/src/coralnpu"
mkdir -p "$OUT/split"
rm -rf "$OUT/split"/*
unzip -q -o "$BIN/CoreMiniAxi.zip" -d "$OUT/split"
cp "$BIN/CoreMiniAxi.sv" "$OUT/split/"
# Order: packages first, then external resources, then the Chisel-emitted
# design (single-file emit already contains every Chisel module, so drop the
# split per-module copies to avoid duplicate definitions).
python3 - "$OUT" <<'PY'
import os, re, sys
out = sys.argv[1]; split = os.path.join(out, "split")
files = []
for d, _, fs in os.walk(split):
    for f in fs:
        if f.endswith((".sv", ".v", ".svh")): files.append(os.path.relpath(os.path.join(d, f), split))
single = open(os.path.join(split, "CoreMiniAxi.sv")).read()
emitted = set(re.findall(r"^module\s+(\w+)", single, re.M))
def is_dup(path):
    txt = open(os.path.join(split, path)).read()
    mods = set(re.findall(r"^module\s+(\w+)", txt, re.M))
    return path != "CoreMiniAxi.sv" and mods and mods <= emitted
keep = [f for f in files if not is_dup(f) and not f.endswith(".f")]
pkgs = sorted(f for f in keep if "_pkg" in f)
rest = sorted(f for f in keep if f not in pkgs and f != "CoreMiniAxi.sv")
order = pkgs + rest + ["CoreMiniAxi.sv"]
with open(os.path.join(out, "coralnpu_core_mini_axi.sv"), "w") as w:
    w.write("// Flattened Coral NPU CoreMiniAxi bundle. Generated by export-coralnpu-sv.sh.\n")
    w.write("`define USE_GENERIC 1\n")
    for f in order:
        w.write("\n// ===== %s =====\n" % f)
        w.write(open(os.path.join(split, f)).read())
        w.write("\n")
open(os.path.join(out, "coralnpu_core_mini_axi.f"), "w").write("\n".join(order) + "\n")
print("wrote", os.path.join(out, "coralnpu_core_mini_axi.sv"), "from", len(order), "files")
PY
python3 "$ROOT/platforms/chipyard/tools/check_ports.py" "$OUT/coralnpu_core_mini_axi.sv"
echo "export CORALNPU_SV=$OUT/coralnpu_core_mini_axi.sv"
