// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Top level: 8 Coral NPU tiles around a central Snitch cluster hub,
// connected by a 3x3 FlooNoC mesh with XY routing.
//
//   y=2  [coral_w 2]--[R 0,2]---[R 1,2]---[R 2,2]--[coral_e 2]
//                                  | coral_n
//   y=1  [coral_w 1]--[R 0,1]---[R 1,1]---[R 2,1]--[coral_e 1]
//            host (W)-/            | snitch           \-mem (E)
//   y=0  [coral_w 0]--[R 0,0]---[R 1,0]---[R 2,0]--[coral_e 0]
//                                  | coral_s
//
// The NoC (routers, chimneys, address map) is generated by FlooGen from
// floogen/coralnpu_snitch_mesh_3x3.yml. Coral tile sideband signals are
// arranged as flat [7:0] vectors in the order:
//   0-2: coral_w y=0..2, 3-5: coral_e y=0..2, 6: coral_n, 7: coral_s

module coralnpu_snitch_mesh
  import floo_coralnpu_snitch_mesh_noc_pkg::*;
#(
  parameter int unsigned NumCoralTiles  = 8,
  parameter int unsigned NrSnitchCores  = 9
) (
  input  logic clk_i,
  input  logic rst_ni,
  input  logic test_enable_i,

  // Coral tile sideband (indexing described above)
  input  logic [NumCoralTiles-1:0][31:0] coral_boot_addr_i,
  input  logic [NumCoralTiles-1:0]       coral_irq_i,
  output logic [NumCoralTiles-1:0]       coral_halted_o,
  output logic [NumCoralTiles-1:0]       coral_fault_o,
  output logic [NumCoralTiles-1:0]       coral_wfi_o,

  // Snitch cluster sideband
  input  logic [NrSnitchCores-1:0] snitch_debug_req_i,
  input  logic [NrSnitchCores-1:0] snitch_meip_i,
  input  logic [NrSnitchCores-1:0] snitch_mtip_i,
  input  logic [NrSnitchCores-1:0] snitch_msip_i,
  input  logic [31:0]              snitch_hart_base_id_i,

  // Host manager port (external CPU: program load, CSR control)
  input  axi_in_req_t  host_axi_req_i,
  output axi_in_rsp_t  host_axi_rsp_o,

  // Shared external memory subordinate port
  output axi_out_req_t mem_axi_req_o,
  input  axi_out_rsp_t mem_axi_rsp_i
);

  axi_in_req_t  [NumCoralTiles-1:0] coral_mgr_req;
  axi_in_rsp_t  [NumCoralTiles-1:0] coral_mgr_rsp;
  axi_out_req_t [NumCoralTiles-1:0] coral_sbr_req;
  axi_out_rsp_t [NumCoralTiles-1:0] coral_sbr_rsp;

  for (genvar i = 0; i < NumCoralTiles; i++) begin : gen_coral
    coralnpu_floo_tile #(
      .axi_in_req_t  (axi_in_req_t),
      .axi_in_rsp_t  (axi_in_rsp_t),
      .axi_out_req_t (axi_out_req_t),
      .axi_out_rsp_t (axi_out_rsp_t)
    ) u_tile (
      .clk_i         (clk_i),
      .rst_ni        (rst_ni),
      .test_enable_i (test_enable_i),
      .boot_addr_i   (coral_boot_addr_i[i]),
      .irq_i         (coral_irq_i[i]),
      .halted_o      (coral_halted_o[i]),
      .fault_o       (coral_fault_o[i]),
      .wfi_o         (coral_wfi_o[i]),
      .axi_mgr_req_o (coral_mgr_req[i]),
      .axi_mgr_rsp_i (coral_mgr_rsp[i]),
      .axi_sbr_req_i (coral_sbr_req[i]),
      .axi_sbr_rsp_o (coral_sbr_rsp[i])
    );
  end

  axi_in_req_t  snitch_mgr_req;
  axi_in_rsp_t  snitch_mgr_rsp;
  axi_out_req_t snitch_sbr_req;
  axi_out_rsp_t snitch_sbr_rsp;

  snitch_floo_hub #(
    .HubBaseAddr   (48'h0000_2000_0000),
    .NrCores       (NrSnitchCores),
    .axi_in_req_t  (axi_in_req_t),
    .axi_in_rsp_t  (axi_in_rsp_t),
    .axi_out_req_t (axi_out_req_t),
    .axi_out_rsp_t (axi_out_rsp_t)
  ) u_snitch_hub (
    .clk_i          (clk_i),
    .rst_ni         (rst_ni),
    .debug_req_i    (snitch_debug_req_i),
    .meip_i         (snitch_meip_i),
    .mtip_i         (snitch_mtip_i),
    .msip_i         (snitch_msip_i),
    .hart_base_id_i (snitch_hart_base_id_i),
    .axi_mgr_req_o  (snitch_mgr_req),
    .axi_mgr_rsp_i  (snitch_mgr_rsp),
    .axi_sbr_req_i  (snitch_sbr_req),
    .axi_sbr_rsp_o  (snitch_sbr_rsp)
  );

  floo_coralnpu_snitch_mesh_noc u_noc (
    .clk_i                 (clk_i),
    .rst_ni                (rst_ni),
    .test_enable_i         (test_enable_i),
    .coral_w_axi_in_req_i  (coral_mgr_req[2:0]),
    .coral_w_axi_in_rsp_o  (coral_mgr_rsp[2:0]),
    .coral_w_axi_out_req_o (coral_sbr_req[2:0]),
    .coral_w_axi_out_rsp_i (coral_sbr_rsp[2:0]),
    .coral_e_axi_in_req_i  (coral_mgr_req[5:3]),
    .coral_e_axi_in_rsp_o  (coral_mgr_rsp[5:3]),
    .coral_e_axi_out_req_o (coral_sbr_req[5:3]),
    .coral_e_axi_out_rsp_i (coral_sbr_rsp[5:3]),
    .coral_n_axi_in_req_i  (coral_mgr_req[6]),
    .coral_n_axi_in_rsp_o  (coral_mgr_rsp[6]),
    .coral_n_axi_out_req_o (coral_sbr_req[6]),
    .coral_n_axi_out_rsp_i (coral_sbr_rsp[6]),
    .coral_s_axi_in_req_i  (coral_mgr_req[7]),
    .coral_s_axi_in_rsp_o  (coral_mgr_rsp[7]),
    .coral_s_axi_out_req_o (coral_sbr_req[7]),
    .coral_s_axi_out_rsp_i (coral_sbr_rsp[7]),
    .snitch_axi_in_req_i   (snitch_mgr_req),
    .snitch_axi_in_rsp_o   (snitch_mgr_rsp),
    .snitch_axi_out_req_o  (snitch_sbr_req),
    .snitch_axi_out_rsp_i  (snitch_sbr_rsp),
    .host_axi_in_req_i     (host_axi_req_i),
    .host_axi_in_rsp_o     (host_axi_rsp_o),
    .mem_axi_out_req_o     (mem_axi_req_o),
    .mem_axi_out_rsp_i     (mem_axi_rsp_i)
  );

endmodule
