// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Top level: a mesh of Coral NPU tiles connected by a FlooNoC network.
//
//        y=1   [coral 0,1]--[R 0,1]----[R 1,1]--[coral 1,1]
//                             |          |  \
//                             |          |   `-- mem (East)
//        y=0   [coral 0,0]--[R 0,0]----[R 1,0]--[coral 1,0]
//                          /
//               host (West)
//
// The NoC itself (routers, chimneys, system address map) is generated by
// FlooGen from floogen/coralnpu_mesh_2x2.yml into
// generated/floo_coralnpu_mesh_noc.sv. This module instantiates the
// generated network and one coralnpu_floo_tile per mesh position, and
// exposes the host manager port and the shared-memory subordinate port.

module coralnpu_floo_mesh
  import floo_coralnpu_mesh_noc_pkg::*;
(
  input  logic clk_i,
  input  logic rst_ni,
  input  logic test_enable_i,

  // Per-tile sideband, indexed [x][y]
  input  logic [NumCoralX-1:0][NumCoralY-1:0][31:0] boot_addr_i,
  input  logic [NumCoralX-1:0][NumCoralY-1:0]       irq_i,
  output logic [NumCoralX-1:0][NumCoralY-1:0]       halted_o,
  output logic [NumCoralX-1:0][NumCoralY-1:0]       fault_o,
  output logic [NumCoralX-1:0][NumCoralY-1:0]       wfi_o,

  // Host manager port (external CPU: program load, CSR control)
  input  axi_in_req_t  host_axi_req_i,
  output axi_in_rsp_t  host_axi_rsp_o,

  // Shared external memory subordinate port
  output axi_out_req_t mem_axi_req_o,
  input  axi_out_rsp_t mem_axi_rsp_i
);

  axi_in_req_t  [NumCoralX-1:0][NumCoralY-1:0] coral_mgr_req;
  axi_in_rsp_t  [NumCoralX-1:0][NumCoralY-1:0] coral_mgr_rsp;
  axi_out_req_t [NumCoralX-1:0][NumCoralY-1:0] coral_sbr_req;
  axi_out_rsp_t [NumCoralX-1:0][NumCoralY-1:0] coral_sbr_rsp;

  for (genvar x = 0; x < NumCoralX; x++) begin : gen_x
    for (genvar y = 0; y < NumCoralY; y++) begin : gen_y
      coralnpu_floo_tile u_tile (
        .clk_i         (clk_i),
        .rst_ni        (rst_ni),
        .test_enable_i (test_enable_i),
        .boot_addr_i   (boot_addr_i[x][y]),
        .irq_i         (irq_i[x][y]),
        .halted_o      (halted_o[x][y]),
        .fault_o       (fault_o[x][y]),
        .wfi_o         (wfi_o[x][y]),
        .axi_mgr_req_o (coral_mgr_req[x][y]),
        .axi_mgr_rsp_i (coral_mgr_rsp[x][y]),
        .axi_sbr_req_i (coral_sbr_req[x][y]),
        .axi_sbr_rsp_o (coral_sbr_rsp[x][y])
      );
    end
  end

  floo_coralnpu_mesh_noc u_noc (
    .clk_i               (clk_i),
    .rst_ni              (rst_ni),
    .test_enable_i       (test_enable_i),
    .coral_axi_in_req_i  (coral_mgr_req),
    .coral_axi_in_rsp_o  (coral_mgr_rsp),
    .coral_axi_out_req_o (coral_sbr_req),
    .coral_axi_out_rsp_i (coral_sbr_rsp),
    .host_axi_in_req_i   (host_axi_req_i),
    .host_axi_in_rsp_o   (host_axi_rsp_o),
    .mem_axi_out_req_o   (mem_axi_req_o),
    .mem_axi_out_rsp_i   (mem_axi_rsp_i)
  );

endmodule
